env:
  - CODECOV_TOKEN="6a3d8b1b-fe8e-44cb-8b6d-6af0d9344adc"



language: node_js
sudo: false
node_js:
  - 10
  - 9
  - 8
install:
  - npm install
  - sudo pip install codecov
script:
  - npm test
  - npm run report-coverage